version: 2.1

commands:
  long_sleep:
    steps:
      - run:
          name: run long sleep
          command: |
            sleep 30
  cancel_redundant_workflow:
    steps:
      - run:
          name: install cli
          command: |
            bash <(curl https://raw.githubusercontent.com/mkusaka/circli/main/scripts/install.bash)
            ./circli --version
            ./circli workflow cancel_redundant
jobs:
  sleep:
    docker:
      - image: cimg/base:2022.04
    steps:
      - cancel_redundant_workflow
      - long_sleep

workflows:
  version: 2
  build:
    jobs:
      - sleep:
          filters:
            branches:
              only:
                - /check-redundant\/.*/
