name: auto release

on:
  pull_request:
    types:
      - closed

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: if workflow not merged
        if: ${{ github.event.pull_request.merged == false }}
        run: |
          gh run cancel "$GITHUB_RUN_ID"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
  release_tag:
    needs:
      - release
    uses: ./.github/workflows/release_tag.yml
  release_build:
    needs:
      - release_tag
    uses: ./.github/workflows/gh-release.yml
