name: auto release

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ github.event.pull_request.merged == true }}
        uses: actions/checkout@v3
      - uses: github.com/mkusaka/circli/.github/workflows/release_tag.yml
      - uses: github.com/mkusaka/circli/.github/workflows/gh-release.yml
