name: release artifact

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
  workflow_call:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '1.22.0'
      - name: install deps
        run: yarn install --check-files
      - name: Release
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG: $TAG"
          gh release create "$TAG" --generate-notes
          yarn upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
