name: create release tag
on:
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download nsv
        run: |
          bash <(curl https://raw.githubusercontent.com/mkusaka/next-semantic-version-cli/main/scripts/install.bash)
          git tag "v$(nsv "$(git describe --tags --abbrev=0)")"
          git push --tags
