name: create release tag
on:
  workflow_dispatch:
  workflow_call:

permissions: write-all

jobs:
  release_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0
      - name: Download nsv
        run: |
          bash <(curl https://raw.githubusercontent.com/mkusaka/next-semantic-version-cli/main/scripts/install.bash)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          TAG="$(./nsv "$(git describe --tags --abbrev=0)")"
          RELEASE_TAG="v$TAG"
          git tag "$RELEASE_TAG"
          git push --tags
